version: '3.5'

services:
  webserver:
    container_name: webserver
    build:
      context: ./docker/nginx
      args:
        UID: $U_ID
    ports:
      - 8080:80
    volumes:
      - ./public:/app/public
    networks:
      - stackoverflow-network
    depends_on:
      - php-fpm

  php-fpm:
    container_name: php-fpm
    build:
      context: ./docker/php
      args:
        UID: $U_ID
    environment:
      PHP_IDE_CONFIG: serverName=Docker
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_CONFIG: remote_host=172.17.0.1 remote_port=9005 # Linux users
#      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9005 # MacOS users
    volumes:
      - ./:/app
      - ./docker/php/xdebug-linux.ini:/usr/local/etc/php/conf.d/xdebug.ini # Linux users
#    - ./docker/php/xdebug-macos.ini:/usr/local/etc/php/conf.d/xdebug.ini # MacOS users
      - ~/.ssh/id_rsa:/home/appuser/.ssh/id_rsa
    networks:
      - stackoverflow-network

networks:
  stackoverflow-network:
    external: true